name: Build and Run

on: [push]

jobs:
  windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: download and extract libvpx
      run: |
        curl -sSfL -O https://github.com/ShiftMediaProject/libvpx/releases/download/v1.8.2/libvpx_v1.8.2_msvc16.zip
        unzip libvpx_v1.8.2_msvc16.zip -d $HOME\unzipped
        dir
        dir $HOME\unzipped
        dir $HOME\unzipped\lib\x64
    - name: Run test
      run: |
        cd vpx-sys-test
        $Env:VPX_STATIC = "1"
        $Env:VPX_VERSION = "1.8.2"
        $Env:VPX_LIB_DIR = "$HOME\unzipped\lib\x64"
        $Env:VPX_INCLUDE_DIR = "$HOME\unzipped\include"
        $Env:VPX_LIB_DIR
        cargo run

  windows-latest-vpx190:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: download and extract libvpx
      run: |
        curl -sSfL -O  https://github.com/ShiftMediaProject/libvpx/releases/download/v1.9.0/libvpx_v1.9.0_msvc16.zip
        unzip libvpx_v1.9.0_msvc16.zip -d $HOME\unzipped
        dir
        dir $HOME\unzipped
        dir $HOME\unzipped\lib\x64
    - name: Run test
      run: |
        cd vpx-sys-test
        $Env:VPX_STATIC = "1"
        $Env:VPX_VERSION = "1.9.0"
        $Env:VPX_LIB_DIR = "$HOME\unzipped\lib\x64"
        $Env:VPX_INCLUDE_DIR = "$HOME\unzipped\include"
        $Env:VPX_LIB_DIR
        cargo run

  macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: download and extract libvpx
      run: |
        cd /tmp
        curl --silent -O -L https://homebrew.bintray.com/bottles/libvpx-1.8.1.sierra.bottle.tar.gz
        sudo mkdir -p /opt
        sudo tar xvzf /tmp/libvpx-1.8.1.sierra.bottle.tar.gz -C /opt
    - name: install rustup
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
    - name: Run test
      run: |
        cd vpx-sys-test
        export VPX_VERSION=1.8.1
        export VPX_STATIC=1
        export VPX_LIB_DIR="/opt/libvpx/1.8.1/lib"
        export VPX_INCLUDE_DIR="/opt/libvpx/1.8.1/include"
        export PATH="$PATH:$HOME/.cargo/bin"
        cargo run

  linux-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: download and extract libvpx
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libvpx-dev
    - name: Run test
      run: |
        cd vpx-sys-test
        cargo run
